### PR TITLE
Add basic examples for other test clients and change structure of `examples` folder

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

This PR adds basic examples for other test-clients - HTTP Producer & Consumer, Kafka Producer & Consumer & Streams.
Also it changes structure of `examples` folder little bit:

```
examples
├── http
│   ├── http-consumer.yaml
│   └── http-producer.yaml
└── kafka
    ├── admin-client
    │   ├── alter-topics.yaml
    │   ├── create-topics.yaml
    │   ├── delete-topics.yaml
    │   ├── delete-with-offset-scram512.yaml
    │   ├── delete-with-offset.yaml
    │   └── list-topics.yaml
    ├── kafka-consumer.yaml
    ├── kafka-producer.yaml
    └── kafka-streams.yaml
```

### CODE REVIEW

**Review by Frawless — APPROVED** [review]

**Review by scholzj — APPROVED** [review]
Out of curiosity ... are you actually using these in the operator STs? If yes, should it still be called _examples_? Or why are they useful?

**Comment by im-konge** [comment]
When the admin client examples were added, I thought it would be useful to add examples also for other clients - so anyone who would like to test something will just take it, customize it and use it without any difficulties (and thinking what should they add there etc). If it doesn't make sense, I can close it.

**Comment by scholzj** [comment]
> So anyone who would like to test something will just take it, customize it and use it without any difficulties. If it doesn't make sense, I can close it.

So, do you expect this to be more than just an internal implementation detail for the operator STs? Are you ready to talk about versioning, API compatibility etc.? Because you should if you expect / want this to be used by others.

I do not have problem with the examples, but I think you should have an idea about why are you adding them and what will be the expected benefit.

**Comment by im-konge** [comment]
I would say that these examples can be good starting point for anyone new who will write the operators STs - like the admin client examples. If anyone new will not have idea how the yaml should look or where to set envs etc., they can look at these examples.

**Comment by im-konge** [comment]
As we discussed offline, this will be examples for anyone new, who will want to write new STs to operator repository and don't know how to write a `Job`, where to configure env vars etc.

**Pull request merged**
